runtime: python38  # Specify the Python runtime
env: standard       # Using the standard environment

entrypoint: gunicorn -b :$PORT Websv:app  # Replace 'main' with the name of your main Python file without the .py extension

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
